version: '3.8'

services:
  web_server:
   build: ./web
   expose:
     - "80"
   networks: 
      - external
   environment:
    - SRC_FOLDER=/src
    - EXERCISES_FOLDER=/exercises
   volumes: 
     - ${PWD}/web/src/server:/src
     - full-source:/source
     - ${PWD}/web/jwt/server.key:/jwt/server.key
   command: /bin/sh -c 'cd $$SRC_FOLDER && npm run build'
   env_file: ./web/.env
   depends_on:
      - setup
   user: "1000"

  auth_server:
    image: node:17.1.0-alpine3.14
    expose: 
      - "80"
    networks:
      - internal
    volumes: 
      - ./auth_server/src:/src
      - access-list:/access
    command: /bin/sh -c 'node /src/app.js'
    depends_on:
      - setup
    env_file: ./auth_server/.env

  nginx:
    build: ./nginx
    ports:
      - 443:443
    networks:
      - internal
      - external
      - isolate
    volumes:
      - /home/hugo/code/docker/sf_interviewer/nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - /home/hugo/code/docker/sf_interviewer/nginx/tls:/certs
    depends_on:
      - web_server
      - auth_server
    restart: always

  setup:
    build: ./setup
    volumes: 
      - ${PWD}/setup/source/exercises:/source
      - exercises-source:/mnt/dest
    
networks:
  internal:
    internal: true
  isolate:
    internal: true
  external:
 
volumes:
  exercises-source:
  full-source:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/setup/source
  access-list:
   driver: local
   driver_opts:
    type: none
    o: bind
    device: ${PWD}/auth_server/access
